services:
  typebot-db:
    image: postgres:13
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    command: ["postgres","-p","5433", "-c", "log_line_prefix="]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d typebot -p 5433"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
  typebot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    depends_on:
      typebot-db:
        condition: service_healthy
    ports:
      - '3002:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
  typebot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    ports:
      - '3003:3000'
    env_file: .env
    environment:
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_ENV=production
      - DD_SERVICE=typebot-viewer
      - DD_VERSION=1.0
