apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: typebot

resources:
  - namespace.yaml
  - typebot-builder-configmap.yaml
  - typebot-builder-deployment.yaml
  - typebot-builder-ingress.yaml
  - typebot-builder-service.yaml
  - typebot-builder-hpa.yaml
  - typebot-viewer-configmap.yaml
  - typebot-viewer-deployment.yaml
  - typebot-viewer-ingress.yaml
  - typebot-viewer-service.yaml
  - typebot-viewer-hpa.yaml
