apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: typebot-viewer
  name: typebot-viewer
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: typebot-viewer
  targetCPUUtilizationPercentage: 125
