apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: typebot-viewer
  name: typebot-viewer
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: typebot-viewer
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 125
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 200
