apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: typebot-viewer-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: eddieeyes.us-east-1.dev.cloudhumans.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: typebot
                port:
                  name: http-viewer
  tls:
    - hosts:
        - eddieeyes.us-east-1.dev.cloudhumans.io
      secretName: typebot-viewer-tls-secret
