# See https://fly.io/docs/reference/configuration/

app = 'typebot-io-io7jag'
primary_region = 'fra'

kill_signal = "SIGTERM"
kill_timeout = 120

[build]
dockerfile = "Dockerfile"

  [build.args]
    DATABASE_URL = "mysql://"

[http_service]
  internal_port = 3007
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "10s"
    method = "GET"
    path = "/healthz"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
