# See https://fly.io/docs/reference/configuration/

app = 'typebot-io-io7jag'
primary_region = 'fra'

kill_signal = "SIGTERM"
kill_timeout = 120

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 3007
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks.health]
  grace_period = "30s"
  interval = "15s"
  timeout = "10s"
  port = 3007
  type = "http"
  method = "GET"
  path = "/healthz"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
