name: Daily job

on:
  schedule:
    - cron: "30 5 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/scripts
    env:
      DATABASE_URL: "${{ secrets.DATABASE_URL }}"
      DATABASE_URL_REPLICA: "${{ secrets.DATABASE_URL_REPLICA }}"
      ENCRYPTION_SECRET: "${{ secrets.ENCRYPTION_SECRET }}"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXT_PUBLIC_VIEWER_URL: "http://localhost:3001"
      MESSAGE_WEBHOOK_URL: "${{ secrets.MESSAGE_WEBHOOK_URL }}"
      POSTHOG_PROJECT_ID: "${{ secrets.POSTHOG_PROJECT_ID }}"
      POSTHOG_DAILY_DASHBOARD_ID: "${{ secrets.POSTHOG_DAILY_DASHBOARD_ID }}"
      NEXT_PUBLIC_POSTHOG_KEY: "${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}"
      POSTHOG_API_HOST: "${{ secrets.POSTHOG_API_HOST }}"
      POSTHOG_PERSONAL_API_KEY: "${{ secrets.POSTHOG_PERSONAL_API_KEY }}"
      STRIPE_SECRET_KEY: "${{ secrets.STRIPE_SECRET_KEY }}"
      OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
      DISCORD_CHANNEL_ID: "${{ secrets.DISCORD_CHANNEL_ID }}"
      DISCORD_BOT_TOKEN: "${{ secrets.DISCORD_BOT_TOKEN }}"
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"
      - run: bun install
      - run: bunx turbo run cron:daily
